export const apidata = {
    "status": "ok",
    "request_id": "12be6a82-c433-11ee-a81d-42004e494300",
    "start_time": "2024-02-05 14:30:09",
    "finish_time": "2024-02-05 14:30:13",
    "data": [
      {
        "asin": "B08PNM1LNZ",
        "title": "Apple iPhone 12, 64GB, Blue - Fully Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B08PNM1LNZ",
        "image": "https://m.media-amazon.com/images/I/61pz7VA6KoL._AC_UY218_.jpg",
        "price": "$304.00",
        "original_price": "$397.76",
        "stars": 4.2,
        "rating_count": 16512,
        "bought_in_past_month": null,
        "is_prime": true,
        "is_best_seller": true,
        "is_climate_pledge_friendly": false,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B08PNN2SKF",
        "title": "Apple iPhone 12 Mini, 64GB, Blue - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B08PNN2SKF",
        "image": "https://m.media-amazon.com/images/I/61M5w4HMIJL._AC_UY218_.jpg",
        "price": "$248.00",
        "original_price": "$311.76",
        "stars": 4.2,
        "rating_count": 10028,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B07ZPJW2XH",
        "title": "Apple iPhone 11, 64GB, White - Fully Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B07ZPJW2XH",
        "image": "https://m.media-amazon.com/images/I/31PY10NqSLL._AC_UY218_.jpg",
        "price": "$248.99",
        "original_price": "$264.00",
        "stars": 4.3,
        "rating_count": 46779,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B07P83CBGR",
        "title": "Apple iPhone XR, US Version, 128GB, White - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B07P83CBGR",
        "image": "https://m.media-amazon.com/images/I/61U15mbXKNL._AC_UY218_.jpg",
        "price": "$214.95",
        "original_price": null,
        "stars": 4.5,
        "rating_count": 62866,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B09LNFRHGN",
        "title": "Apple iPhone 13, 256GB, Blue - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B09LNFRHGN",
        "image": "https://m.media-amazon.com/images/I/71H8ipbuxoL._AC_UY218_.jpg",
        "price": "$489.95",
        "original_price": null,
        "stars": 4.3,
        "rating_count": 5434,
        "bought_in_past_month": null,
        "is_prime": true,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B0BN92X6XK",
        "title": "Apple iPhone 14 Pro, 128GB, Deep Purple - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B0BN92X6XK",
        "image": "https://m.media-amazon.com/images/I/518bzP8VW1L._AC_UY218_.jpg",
        "price": "$689.00",
        "original_price": "$859.00",
        "stars": 4.2,
        "rating_count": 985,
        "bought_in_past_month": null,
        "is_prime": true,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B07C357FSJ",
        "title": "Apple iPhone X, US Version, 64GB, Silver - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B07C357FSJ",
        "image": "https://m.media-amazon.com/images/I/81SSw14XZHL._AC_UY218_.jpg",
        "price": "$170.00",
        "original_price": "$189.95",
        "stars": 4.2,
        "rating_count": 24253,
        "bought_in_past_month": null,
        "is_prime": true,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B08PNP5YGV",
        "title": "Apple iPhone 12 Pro, 128GB, Graphite - Fully Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B08PNP5YGV",
        "image": "https://m.media-amazon.com/images/I/51bf95umgzL._AC_UY218_.jpg",
        "price": "$379.99",
        "original_price": "$521.01",
        "stars": 4.2,
        "rating_count": 8347,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B0CNY9HRKJ",
        "title": "Apple iPhone 8 64GB Silver Unlocked",
        "url": "https://www.amazon.com/dp/B0CNY9HRKJ",
        "image": "https://m.media-amazon.com/images/I/51NtvVpxXhL._AC_UY218_.jpg",
        "price": "$138.59",
        "original_price": "$165.00",
        "stars": 4,
        "rating_count": 23,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B0CNL7DMZC",
        "title": "Apple iPhone 8 64GB Unlocked - Gold",
        "url": "https://www.amazon.com/dp/B0CNL7DMZC",
        "image": "https://m.media-amazon.com/images/I/61aZ+koDWKL._AC_UY218_.jpg",
        "price": "$127.00",
        "original_price": "$165.00",
        "stars": 4,
        "rating_count": 25,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": false,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B0BN71VW28",
        "title": "Apple iPhone 14, 128GB, Purple - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B0BN71VW28",
        "image": "https://m.media-amazon.com/images/I/619f09kK7tL._AC_UY218_.jpg",
        "price": "$548.99",
        "original_price": "$579.85",
        "stars": 4.3,
        "rating_count": 1314,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B07ZQPYXJP",
        "title": "Apple iPhone 11 Pro, 256GB, Midnight Green - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B07ZQPYXJP",
        "image": "https://m.media-amazon.com/images/I/51vusZ4p2tL._AC_UY218_.jpg",
        "price": "$333.94",
        "original_price": "$349.79",
        "stars": 4.2,
        "rating_count": 19987,
        "bought_in_past_month": null,
        "is_prime": true,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B08PL89SJS",
        "title": "Apple iPhone 12 Pro Max 5G, US Version, 128GB, Graphite - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B08PL89SJS",
        "image": "https://m.media-amazon.com/images/I/61I39htrBbL._AC_UY218_.jpg",
        "price": "$474.95",
        "original_price": "$546.00",
        "stars": 4.1,
        "rating_count": 4933,
        "bought_in_past_month": null,
        "is_prime": true,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B088NKV4QJ",
        "title": "Apple iPhone SE (2nd Generation), US Version, 64GB, Black for T-Mobile (Renewed)",
        "url": "https://www.amazon.com/dp/B088NKV4QJ",
        "image": "https://m.media-amazon.com/images/I/813ovO0PGGL._AC_UY218_.jpg",
        "price": "$147.00",
        "original_price": null,
        "stars": 4.3,
        "rating_count": 15976,
        "bought_in_past_month": null,
        "is_prime": true,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B07K4VCLLK",
        "title": "Apple iPhone XS, 64GB, Silver - Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B07K4VCLLK",
        "image": "https://m.media-amazon.com/images/I/61BXfa66w7L._AC_UY218_.jpg",
        "price": "$180.00",
        "original_price": "$196.00",
        "stars": 4.3,
        "rating_count": 2409,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      },
      {
        "asin": "B07758RMKD",
        "title": "Apple Iphone X, 256GB, Space Gray - Fully Unlocked (Renewed)",
        "url": "https://www.amazon.com/dp/B07758RMKD",
        "image": "https://m.media-amazon.com/images/I/719knfTwPvL._AC_UY218_.jpg",
        "price": "$202.99",
        "original_price": "$1,104.03",
        "stars": 4.1,
        "rating_count": 2078,
        "bought_in_past_month": null,
        "is_prime": false,
        "is_best_seller": false,
        "is_climate_pledge_friendly": true,
        "is_limited_time_deal": false,
        "is_sponsored": false
      }
    ]
  }